# This is a basic workflow to help you get started with Actions

name: LoadAndPack

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # install nodejs
      - uses: actions/setup-node@v3.9.1

      # install docker CE
      # - uses: docker/setup-docker-action@v4.3.0
      
      # prepare lzc-cli and env
      - name: install lzc-cli etc.
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          npm install -g @lazycatcloud/lzc-cli
          sudo apt install expect curl -y
          chmod +x int.exp
          ./int.exp
      
      # load msyh.ttc
      - name: get font
        run: |
          mkdir -p ./content/fonts/
          curl -L "https://github.com/fernvenue/microsoft-yahei/raw/refs/heads/master/msyh.ttc" -o ./content/fonts/msyh.ttc
          
      # replace manifest
      - name: fetch image
        run: |
          last_part=$(lzc-cli appstore copy-image linuxserver/chromium | tail -n 1 | awk '{print $NF}')
          today=$(date +"%y.%-m.%-d")
          sed -i "s/##/$last_part/" lzc-manifest.yml
          sed -i "s/^version: .*/version: $today/I" lzc-manifest.yml
        
      # build
      - name: build
        run: |
          lzc-cli project build
      
      # upload
      - uses: actions/upload-artifact@v4.6.2
        with:
          path: ./*.lpk
